#!/usr/bin/perl
use strict;
use feature "say";
use JSON;
use Tie::IxHash;

my %dois;
my $symbol = "ETHZ.UNKNOWN",

open HANDLE, $ARGV[0];
while (<HANDLE>) {
  chomp;
  my ($doi, $timestamp) = split "\t";
  $doi =~ tr/a-z/A-Z/;
  $timestamp =~ s/ /T/;
  $timestamp .= "Z";
  my ($prefix) = split "/",$doi;
  $dois{$doi} = {
    doi => $doi,
    prefix => $prefix,
    minted => $timestamp,
    allocator_symbol => "ETHZ",
    allocator => "ETHZ - ETH Zurich",
    datacentre_symbol => "$symbol",
    datacentre => "$symbol - not assigned to a specific ETHZ datacentre",
    dataset_id => "dummy-$doi",
    is_active => "true",
    has_metadata => "false",
    has_media => "false"
  }
}
close HANDLE;

open SEARCH, $ARGV[1];
while (<SEARCH>) {
  chomp;
  tr/a-z/A-Z/;
  delete $dois{$_};
}
close SEARCH;

my @dois = values %dois;

tie my %solr, 'Tie::IxHash';
$solr{delete} = { query => "datacentre_symbol:$symbol" };
$solr{add} = \@dois;

say to_json \%solr;

