#!/bin/bash
servers="tib eth"
total=0
echo -e "Server\tDOIs\tLast Creation"
for server in $servers; do
  sql="SELECT UPPER('${server}'), COUNT(*), FROM_UNIXTIME(MAX(timestamp))
       FROM handle_${server}_replica.handles 
       WHERE type = 'HS_ADMIN'"
  response=`mysql $DATACITE_MYSQL --skip-column-names --batch -e "$sql"`
  echo "$response"
  count=`echo "$response" | cut -f 2`
  let "total += count"
done
echo -e "-------\t-------"
echo -e "total\t$total"
